### ISSUE TITLE
Add trailing newline to toc

### ISSUE THREAD

**Issue by dreh23** [adr/madr#26]
The autogenerated TOC has no trailing newline. 

This is problematic if you run a markdown linter that lints according to the commonmark spec. Since we autogenerate (adr -u) the TOC and we do linting in a continuous integration context this always fails. 

A flag for adr -u to add a newline after generation would be useful.

`README.md:3 MD047/single-trailing-newline Files should end with a single newline character`

**Comment by koppor** [comment]
I wonder which tool you are using. This repository does not offer any comamnd line tool(yet). [adr-log](https://github.com/adr/adr-log) does not offer `-u`. Is it [our fork of adr-tools](https://github.com/adr/adr-tools)? This does not support `-u`, does it?

I would like to work on a fix, since I also make heavy use of [markdown-lint](https://github.com/DavidAnson/markdownlint/#markdownlint) and a GitHub action workflow:

```yaml
name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Lint all files
        uses: avto-dev/markdown-lint@v1
        with:
          args: 'en/'
          config: '.markdownlint.yml'
```
